# Generated by Django 4.0.6 on 2022-07-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Familia', '0002_rename_parentezco_familiar_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('amigodesde', models.IntegerField()),
            ],
        ),
    ]
