# Generated by Django 4.0.6 on 2022-07-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Familia', '0004_estudios_trabajos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiar',
            options={'ordering': ('nombre', '-edad'), 'verbose_name': 'family', 'verbose_name_plural': 'My familys'},
        ),
        migrations.AddField(
            model_name='estudios',
            name='familiar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_Familia.familiar'),
        ),
        migrations.AlterUniqueTogether(
            name='familiar',
            unique_together={('nombre', 'apellido')},
        ),
    ]
