# Generated by Django 4.0.6 on 2022-07-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Familia', '0005_alter_familiar_options_estudios_familiar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudios',
            old_name='profesor',
            new_name='universidad',
        ),
    ]
