# Generated by Django 4.0.6 on 2022-07-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Familia', '0006_rename_profesor_estudios_universidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Familia.familiar'),
        ),
    ]
